<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="ValidationResult">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="Valid" type="xs:string"/>

                <xs:element name="PurchaseOrders">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="Item">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Vendor" type="xs:string"/>
                                        <xs:element name="Material" type="xs:string"/>
                                        <xs:element name="Plant" type="xs:string"/>
                                        <xs:element name="Quantity" type="xs:string"/>
                                        <xs:element name="Price" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
